# Generated by Django 5.2.6 on 2025-09-24 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('cliente_id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.TextField()),
                ('idade', models.IntegerField(blank=True, null=True)),
                ('nif', models.IntegerField(blank=True, null=True, unique=True)),
                ('morada', models.TextField(blank=True, null=True)),
                ('email', models.TextField(blank=True, null=True, unique=True)),
            ],
            options={
                'db_table': 'cliente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Destino',
            fields=[
                ('destino_id', models.IntegerField(primary_key=True, serialize=False)),
                ('pais', models.TextField()),
                ('cidade', models.TextField()),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'destino',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Fatura',
            fields=[
                ('fatura_id', models.AutoField(primary_key=True, serialize=False)),
                ('data_emissao', models.DateField()),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'fatura',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('feedback_id', models.AutoField(primary_key=True, serialize=False)),
                ('data_feedback', models.DateField()),
                ('avaliacao', models.IntegerField()),
                ('comentario', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'feedback',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('hotel_id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
                ('morada', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'hotel',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pacote',
            fields=[
                ('pacote_id', models.AutoField(primary_key=True, serialize=False)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pacote',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('pagamento_id', models.AutoField(primary_key=True, serialize=False)),
                ('data_pagamento', models.DateField()),
                ('montante', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'pagamento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('reserva_id', models.AutoField(primary_key=True, serialize=False)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
            ],
            options={
                'db_table': 'reserva',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Voo',
            fields=[
                ('voo_id', models.AutoField(primary_key=True, serialize=False)),
                ('data_voo', models.DateField()),
                ('hora_partida', models.TimeField()),
                ('hora_chegada', models.TimeField()),
                ('duracao', models.DurationField(blank=True, null=True)),
                ('origem', models.CharField(max_length=100)),
                ('porta_embarque', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'voo',
                'managed': False,
            },
        ),
    ]
